# This configuration spins up a client with dummy sensors and publishes via MQTT
# Ideal for testing on a laptop :)
# You can use this to run demos.  Note that at the time of this edit it features ALL
# of the dummy sensors we've created!

Main:
    include_config_files: ["test_config_with_location.yml", "mqtt_config.yml"]

# Here we just add in the dummy sensors that test_config did not already...
Sensors:
    # Dummy environment
    DummyLightSensor:
      class: "dummy.dummy_light_virtual_sensor.DummyLightVirtualSensor"
      dev_name: "light0"
    # Dummy presence_sensors
    DummyPIRSensor:
      class: "dummy.dummy_pir_virtual_sensor.DummyPIRVirtualSensor"
      dev_name: "pir0"
    # VirtualSensors that detect higher-level events: should work with dummy ones
    PIRNoMotionSensor:
      class: "virtual_sensors.pir_no_motion_virtual_sensor.PIRNoMotionVirtualSensor"
      dev_name: "nomot0"
    LightFlashSensor:
      class: "virtual_sensors.light_flash_virtual_sensor.LightFlashVirtualSensor"
      dev_name: "flash0"
    TempHighSensor:
      class: "virtual_sensors.temperature_high_virtual_sensor.TemperatureHighVirtualSensor"
      dev_name: "heat0"