# Note that this still needs a SigfoxEventSink added to it
# Not officially tested!

Main:
    include_config_files: ["mqtt_config.yml"]

Sensors:
    HBSensor:
      class: "network.heartbeat_virtual_sensor.HeartbeatVirtualSensor"
      dev_name: "hb0"
      interval: 60
    TempSensor:
      class: "environment.usb_temperature_virtual_sensor.UsbTemperatureVirtualSensor"
      dev_name: "cel0"
      threshold: 24.0
    # Ensure the CSN client daemon is running and has been configured properly, including the /etc/hosts hack!
    CSNSensor:
      class: "community_seismic_network.csn_virtual_sensor.CSNVirtualSensor"
      dev_name: "accel0"