# Hasn't been officially tested!
Main:
    event_queue_size: 4096

Publishers:
    - MqttPublisher:
        class: "mqtt_publisher.MQTTPublisher"
        hostname: "dime.smartamerica.io"
        #hostname: "m2m.eclipse.org"
        hostport: 1883
        username: null
        #username: "vbjsfwul"
        password: null
        #password: "xottyHH5j9v2"
        keepalive: 60
        #need to insert address before using: topic: "iot-1/d/%012x/evt/%s/json"

Sensors:
    - HBSensor:
        class: "heartbeat_virtual_sensor.HeartbeatVirtualSensor"
        dev_name: "hb0"
        interval: 60
    - PirSensor:
        class: "pir_virtual_sensor.PIRVirtualSensor"
        dev_name: "pir0"
        #gpio_pin: 17
    - LightSensor:
        class: "light_virtual_sensor.LightVirtualSensor"
        dev_name: "light0"
        #analog_port: 3
        threshold: 400
    - GasSensor:
        class: "gas_virtual_sensor.GasVirtualSensor"
        dev_name: "gas0"
        #analog_port: 0
        threshold: 500
    - TempSensor:
        class: "temperature_virtual_sensor.TemperatureVirtualSensor"
        dev_name: "cel0"
        threshold: 24.0
    - SeismicSensor:
        class: "csn_virtual_sensor.CSNVirtualSensor"
        dev_name: "accel"
